#pragma config(Sensor, S3,     seek,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"
task main(){
tHTIRS2 IRseeker;
initSensor(&IRseeker, S3);
IRseeker.mode = DSP_1200;
while(true)
{
	if(IRseeker.acDirection > 5.5)
	{
		eraseDisplay();
		displayStringAt(20, 20, "right");
		displayCenteredTextLine(2,"Value: %f",IRseeker.acDirection);
	}
	else
	{
		eraseDisplay();
		displayStringAt(20, 20, "left");
		displayCenteredTextLine(2,"Value: %f",IRseeker.acDirection);
	}
	readSensor(&IRseeker);
	wait1Msec(50);
}


}
