#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     touch,          sensorI2CMuxController)
#pragma config(Sensor, S2,     armInternal,    sensorTouch)
#pragma config(Sensor, S4,     armExternal,    sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     harvester,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftDrive,     tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S1_C3_1,    flipperServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    lidServo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    goalServo,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{
	return;
}

//#include "library\driveFunctions.c"
#include "library\IRramp.c";

task main()
{
	initializeRobot();

	int msToWait = chooseWait()*1000;//now returns value in SECONDS.

	waitForStart(); // Wait for the beginning of autonomous phase.
	wait1Msec(msToWait);
	playSound(soundBeepBeep);
	//forwardFast(7300);//goes down ramp
	extendArm();//raises arm
	wait1Msec(500);//this wait keeps the arm from damaging itself by moving up and down too quickly
	motor[arm] = -50;//lowers arm slightly
	wait1Msec(2000);
	motor[arm] = 0;
	forwardSlow(1000);//forward to line up with 60cm RG
	wait1Msec(500);
	servo[flipperServo] = 100;//box tilts to scoring position
	wait1Msec(500);
	servo[lidServo] = 200;//lid opens to let small ball out
	wait1Msec(1000);
	extendArm();//raises arm up again
	forwardSlow(3000);
	servo[lidServo] = 223;
	servo[goalServo] = 64;
	fastRightPointTurn(500);
	backwardFast(10000);

	while (true)
	{}
}
