#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     touch,          sensorI2CMuxController)
#pragma config(Sensor, S2,     armInternal,    sensorTouch)
#pragma config(Sensor, S4,     armExternal,    sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     belt,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     harvester,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftDrive,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    lidServo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    flipperServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    goalServo,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{
  return;
}

//#include "library\driveFunctions.c"
#include "library\IRramp.c";

task main()
{
  initializeRobot();

 // chooseWait();

  //wait1Msec(chooseWait());

  waitForStart(); // Wait for the beginning of autonomous phase.

  forwardFast(7300);
  extendArm();
  wait1Msec(500);
  motor[arm] = -50;
  wait1Msec(2000);
  motor[arm] = 0;
  forwardSlow(1000);
  wait1Msec(500);
  servo[flipperServo] = 100;
  wait1Msec(500);
  servo[lidServo] = 200;
  wait1Msec(1000);
  extendArm();
  forwardSlow(3000);
  servo[lidServo] = 223;
  servo[goalServo] = 64;
  fastrightPointTurn(500);
  backwardFast(10000);

  while (true)
  {}
}
