#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     belt,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     harvester,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(MotorPidSetting,  motorA,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(MotorPidSetting,  motorB,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(MotorPidSetting,  motorC,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	while(SensorValue(touchSensor) == 1)
	{
		motor[arm] = 100;
	}
	while(sensorValue(touchSensor) == 0)
	{
		motor[arm] = 100;
	}
	motor[arm] = 0;

}

//motor[arm] = -100;
//wait1Msec(2000);
//motor[arm] = 0;
// while(SensorValue[touch] == 0)
// {
//  if(SensorValue[touch] == 0)
//  {
//  	motor[arm] = 100;
//  }
//  else
//  {
//  	motor[arm] = 0;
//  }
//}
//motor[arm] = 0;
//while(SensorValue[touch] == 0)
// {
//  if(SensorValue[touch] == 0)
//  {
//  	motor[arm] = -100;
//  }
//  else
//  {
//  	motor[arm] = 0;
//  }
//}
////motor[arm] = 0;
////wait1Msec(500);
//if(SensorValue[touch] == 0)
//{
//	motor[arm] = 100;
//}
//motor[arm] = 0;

// while(SensorValue[touch] == 1)//while sensor is pressed the arm goes up
//{
//	motor[arm] = 100;
//}
//motor[arm] = 0;//stop the arm (for troubleshooting)
//wait1Msec(500);
//while(SensorValue[touch] == 0)//while the sensor is not pressed the arm goes the rest of the way up
//{
//	motor[arm] = 100;
//}
//motor[arm] = 0;//motor stops at the top

while (true)
{}
}
